version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - postgresDb:/var/lib/postgres
volumes:
  postgresDb:
